//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeProfile.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AsignClienttoEmp
    {
        public int ID { get; set; }
        public int ClientId { get; set; }
        [Required(ErrorMessage ="Please Enter Client Name")]
        public string ClientName { get; set; }
        public Nullable<int> EID { get; set; }
        [Required(ErrorMessage = "Please Select POS Date")]
        public Nullable<System.DateTime> POS { get; set; }
        [Required(ErrorMessage = "Please Select POE Date")]
        public Nullable<System.DateTime> POE { get; set; }
        [Required(ErrorMessage = "Please Enter Client Billing")]
        public Nullable<decimal> ClientBilling { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        [Required(ErrorMessage = "Please Enter ClientEmail")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                           @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                           @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                           ErrorMessage = "Email is not valid")]
        public string ClientEmail { get; set; }
        [Required(ErrorMessage = "Please Enter Client Manager Name")]
        public string ClientManagerName { get; set; }
        [Required(ErrorMessage = "Please Enter Designation at Client")]
        public string DesignationatClient { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
