//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeDetail()
        {
            this.AsignClienttoEmps = new HashSet<AsignClienttoEmp>();
            this.Bills = new HashSet<Bill>();
            this.ClientMasters = new HashSet<ClientMaster>();
            this.Salaries = new HashSet<Salary>();
        }

        public int EID { get; set; }
        public int EmpId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        [Required(ErrorMessage = "Please Enter Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                            @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                            @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                            ErrorMessage = "Email is not valid")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter Phone Number")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Please Enter Valid Phone Number.")]
        public Nullable<long> Phoneno { get; set; }
        public string Worklocation { get; set; }
        public Nullable<int> Employee_Designation_FK { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SubDepartmentId { get; set; }
        public string LancesoftID { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public Nullable<int> ReportingManagerId { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Pincode { get; set; }
        public Nullable<bool> Active_Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Vertical { get; set; }
        public string Gender { get; set; }
        public string Address_status { get; set; }
        public Nullable<bool> Working_internal { get; set; }
        public Nullable<System.DateTime> Joiningdate { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignClienttoEmp> AsignClienttoEmps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMaster> ClientMasters { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Employee_Type Employee_Type { get; set; }
        public virtual Login Login { get; set; }
        public virtual SubDepartment SubDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salaries { get; set; }
        public decimal ManagerProfit { set; get; }
        public decimal Leadprofit { set; get; }
        public decimal CHProfit { set; get; }
        public decimal GMProfit { set; get; }
    }
}
