//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Sid { get; set; }
        public Nullable<decimal> Salary1 { get; set; }
        public Nullable<System.DateTime> Update_At { get; set; }
        public Nullable<int> EID { get; set; }
        public string Remarks { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
